/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.gnuklub.Looloo;

public final class R {
    public static final class array {
        public static final int MatchingPercentage=0x7f040001;
        public static final int MatchingPercentageValues=0x7f040003;
        public static final int radius=0x7f040000;
        public static final int radiusValues=0x7f040002;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int about=0x7f020000;
        public static final int business=0x7f020001;
        public static final int bussines_big=0x7f020002;
        public static final int education=0x7f020003;
        public static final int education_big=0x7f020004;
        public static final int education_red=0x7f020005;
        public static final int female=0x7f020006;
        public static final int female_big=0x7f020007;
        public static final int female_red=0x7f020008;
        public static final int icon=0x7f020009;
        public static final int info=0x7f02000a;
        public static final int lips=0x7f02000b;
        public static final int logout=0x7f02000c;
        public static final int looloologo=0x7f02000d;
        public static final int male=0x7f02000e;
        public static final int male_big=0x7f02000f;
        public static final int male_red=0x7f020010;
        public static final int mappin_blue=0x7f020011;
        public static final int mappin_red=0x7f020012;
        public static final int monument=0x7f020013;
        public static final int monument_big=0x7f020014;
        public static final int monument_red=0x7f020015;
        public static final int park=0x7f020016;
        public static final int park_big=0x7f020017;
        public static final int park_red=0x7f020018;
        public static final int party=0x7f020019;
        public static final int party_big=0x7f02001a;
        public static final int party_red=0x7f02001b;
        public static final int profile=0x7f02001c;
        public static final int refresh=0x7f02001d;
        public static final int restaurant=0x7f02001e;
        public static final int restaurant_big=0x7f02001f;
        public static final int restaurant_red=0x7f020020;
        public static final int settings=0x7f020021;
        public static final int shopping=0x7f020022;
        public static final int shopping_big=0x7f020023;
        public static final int shopping_red=0x7f020024;
        public static final int sport=0x7f020025;
        public static final int sport_big=0x7f020026;
        public static final int sport_red=0x7f020027;
    }
    public static final class id {
        public static final int PointInfoButtonBack=0x7f06003c;
        public static final int SearchLayout=0x7f060001;
        public static final int WelcomeLayout=0x7f06004d;
        public static final int aboutText=0x7f060000;
        public static final int accountCheckEducationalPlacesColleges=0x7f06002e;
        public static final int accountCheckEducationalPlacesHighSchools=0x7f06002f;
        public static final int accountCheckEducationalPlacesUniversities=0x7f06002d;
        public static final int accountCheckMonumentsAllMonuments=0x7f060029;
        public static final int accountCheckNightBarsBilliardClubs=0x7f060028;
        public static final int accountCheckNightBarsCoffeeBars=0x7f060027;
        public static final int accountCheckNightBarsDiscotheques=0x7f060026;
        public static final int accountCheckRestaurantPizza=0x7f060024;
        public static final int accountCheckRestaurantSushi=0x7f060025;
        public static final int accountCheckShoppingOpenMarkets=0x7f060031;
        public static final int accountCheckShoppingShoppingMalls=0x7f060030;
        public static final int accountCheckSportPlacesRecreationalParks=0x7f06002c;
        public static final int accountCheckSportPlacesSportArenas=0x7f06002a;
        public static final int accountCheckSportPlacesTennisCourts=0x7f06002b;
        public static final int accountDOB=0x7f06000e;
        public static final int accountEmail=0x7f060012;
        public static final int accountGender=0x7f06000a;
        public static final int accountGenderFemale=0x7f06000c;
        public static final int accountGenderMale=0x7f06000b;
        public static final int accountOccupation=0x7f060010;
        public static final int accountPassword=0x7f060008;
        public static final int accountUsername=0x7f060006;
        public static final int apply=0x7f060032;
        public static final int create_new_account_button=0x7f06004f;
        public static final int errorDialogOk=0x7f060033;
        public static final int map=0x7f06003d;
        public static final int next_button=0x7f060013;
        public static final int personDetailsButtonBack=0x7f060043;
        public static final int personDetailsGender=0x7f06003f;
        public static final int personDetailsImage=0x7f06003e;
        public static final int personDetailsInterests=0x7f060042;
        public static final int personDetailsOccupation=0x7f060041;
        public static final int personDetailsYearOfBirth=0x7f060040;
        public static final int pointFocusImage=0x7f060035;
        public static final int pointInfoDescription=0x7f060039;
        public static final int pointInfoMark=0x7f06003b;
        public static final int pointInfoName=0x7f060037;
        public static final int preferencesBookTasteClassics=0x7f06001e;
        public static final int preferencesBookTasteModern=0x7f06001f;
        public static final int preferencesFavoritePastimeComputers=0x7f060020;
        public static final int preferencesFavoritePastimeSports=0x7f060021;
        public static final int preferencesFilmTasteAction=0x7f060016;
        public static final int preferencesFilmTasteComedy=0x7f060019;
        public static final int preferencesFilmTasteDrama=0x7f060017;
        public static final int preferencesFilmTasteHorror=0x7f060018;
        public static final int preferencesLookingForFemale=0x7f060015;
        public static final int preferencesLookingForMale=0x7f060014;
        public static final int preferencesMusicTasteMetal=0x7f06001d;
        public static final int preferencesMusicTastePop=0x7f06001a;
        public static final int preferencesMusicTasteRock=0x7f06001b;
        public static final int preferencesMusicTasteTechno=0x7f06001c;
        public static final int preferencesNext=0x7f060022;
        public static final int serverOutput=0x7f060002;
        public static final int settingsOK=0x7f060046;
        public static final int settingsRadius=0x7f060045;
        public static final int settingsUpdateInt=0x7f060044;
        public static final int signin_edit_password=0x7f06004b;
        public static final int signin_edit_username=0x7f060049;
        public static final int signin_signin_button=0x7f06004c;
        public static final int welcome_singin_button=0x7f06004e;
        public static final int widget0=0x7f060034;
        public static final int widget102=0x7f060047;
        public static final int widget103=0x7f060048;
        public static final int widget104=0x7f06004a;
        public static final int widget118=0x7f060004;
        public static final int widget157=0x7f060023;
        public static final int widget234=0x7f060005;
        public static final int widget235=0x7f060007;
        public static final int widget236=0x7f060009;
        public static final int widget237=0x7f06000d;
        public static final int widget238=0x7f06000f;
        public static final int widget246=0x7f060003;
        public static final int widget29=0x7f06003a;
        public static final int widget301=0x7f060011;
        public static final int widget33=0x7f060036;
        public static final int widget35=0x7f060038;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int advsearch=0x7f030001;
        public static final int create_edit_account_1=0x7f030002;
        public static final int create_edit_account_2=0x7f030003;
        public static final int create_edit_account_3=0x7f030004;
        public static final int error_dialog=0x7f030005;
        public static final int interest_point_focus=0x7f030006;
        public static final int main=0x7f030007;
        public static final int person_details=0x7f030008;
        public static final int settings=0x7f030009;
        public static final int sign_in=0x7f03000a;
        public static final int welcome=0x7f03000b;
    }
    public static final class string {
        public static final int about_name=0x7f050002;
        public static final int advsearch_name=0x7f050003;
        public static final int app_name=0x7f050000;
        public static final int create_edit_account1_name=0x7f050009;
        public static final int create_edit_account2_name=0x7f05000a;
        public static final int create_edit_account3_name=0x7f05000b;
        public static final int defaultPort=0x7f050018;
        /**  <string name="defaultServer">http://192.168.1.34:1337</string> 
         */
        public static final int defaultServer=0x7f050017;
        public static final int editprofile_name=0x7f050004;
        public static final int person_details_name=0x7f05000c;
        public static final int point_info_name=0x7f050006;
        public static final int profile_password=0x7f050015;
        public static final int profile_username=0x7f050014;
        public static final int searchview_name=0x7f050001;
        /**   Za testiranje konekcije sa serverom 
         */
        public static final int serverOutput=0x7f050016;
        public static final int settings_name=0x7f050005;
        public static final int sign_in_name=0x7f050008;
        public static final int svmenu_about=0x7f05000d;
        public static final int svmenu_advsearch=0x7f050010;
        public static final int svmenu_editprofile=0x7f05000f;
        public static final int svmenu_logout=0x7f050013;
        public static final int svmenu_point_info=0x7f050012;
        public static final int svmenu_refresh=0x7f050011;
        public static final int svmenu_settings=0x7f05000e;
        public static final int welcome_name=0x7f050007;
    }
}
